version: 2.1

orbs:
  sonar: hubci/sonar@1.0.0

workflows:
  main-wf:
    jobs:
      - build:
          context: docker-ctx
  nightly-build:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only: trunk
    jobs:
      - build-nightly:
          context: docker-ctx

jobs:
  build:
    docker:
      - image: cimg/base:2023.07
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.24"
      - run:
          name: "Build Docker Images"
          command: |
            sed -e 's/hubci/cibuilds/g' ./build-images.sh > ./build-images-cibuilds.sh
            ./build-images.sh
            chmod +x ./build-images-cibuilds.sh
            ./build-images-cibuilds.sh
      - deploy:
          name: "Publish Docker Images (trunk branch only)"
          command: |
            if [ "${CIRCLE_BRANCH}" == "trunk" ]; then
              
              echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
              
              # an else block will be added in the future for a staging release
              if git log -1 --pretty=%s | grep "\[release\]"; then
                echo "Publishing hubci/hugo to Docker Hub production."
                sed -e 's/hubci/cibuilds/g' ./push-images.sh > ./push-images-cibuilds.sh
                ./push-images.sh
                chmod +x ./push-images-cibuilds.sh
                ./push-images-cibuilds.sh
              else
                echo "Skipping publishing."
              fi
            fi
      - when:
          condition:
            equal: [trunk, << pipeline.git.branch >>]
          steps:
            - sonar/install:
                version: "0.18.0"
            - run: echo 'export DOCKER_PASS=$DOCKER_TOKEN' >> $BASH_ENV
            - sonar/update-readme:
                image: hubci/hugo
  build-nightly:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.24"
      - sonar/install:
          version: "0.19.1"
      - run:
          name: "Build Nightly Docker Image"
          command: ./build-nightly-image.sh
      - run:
          command: |
            echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
            docker push hubci/hugo:nightly
