version: 2.1

orbs:
  sonar: hubci/sonar@1.0.0

workflows:
  main:
    jobs:
      - build:
          context: main-context
  nightly-build:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only: main
    jobs:
      - build-nightly:
          context: main-context

jobs:
  build:
    docker:
      - image: cimg/base:2022.01
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.12"
      - run:
          name: "Build Docker Images"
          command: |
            sed -e 's/hubci/cibuilds/g' ./build-images.sh > ./build-images-cibuilds.sh
            ./build-images.sh
            chmod +x ./build-images-cibuilds.sh
            ./build-images-cibuilds.sh
      - deploy:
          name: "Publish Docker Images (main branch only)"
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              
              echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
              
              # an else block will be added in the future for a staging release
              if git log -1 --pretty=%s | grep "\[release\]"; then
                echo "Publishing hubci/hugo to Docker Hub production."
                sed -e 's/hubci/cibuilds/g' ./push-images.sh > ./push-images-cibuilds.sh
                ./push-images.sh
                chmod +x ./push-images-cibuilds.sh
                ./push-images-cibuilds.sh
              else
                # I'm not sure if this actually runs
                echo "Just publishing an edge image"
                docker tag cibuilds/hugo:latest cibuilds/hugo:edge
                docker push cibuilds/hugo:edge
                docker tag hubci/hugo:latest hubci/hugo:edge
                docker push hubci/hugo:edge
              fi
            fi
      - when:
          condition:
            equal: [main, << pipeline.git.branch >>]
          steps:
            - sonar/install:
                version: "0.15.0"
            - sonar/update-readme:
                image: hubci/hugo
  build-nightly:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.12"
      - run:
          name: "Build Nightly Docker Image"
          command: ./build-nightly-image.sh
      - run:
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push hubci/hugo:nightly
